name: build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yaml
      - src/**
      - acceptance-test/**
      - gradle/**
      - '*.gradle'
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build.yaml
      - src/**
      - acceptance-test/**
      - gradle/**
      - '*.gradle'

jobs:
  gradle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew --no-daemon build

      # publish the example
      - if: github.event_name == 'push'
        run: ./gradlew --no-daemon acceptance-test:example-docs
      - if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./acceptance-test/build
