name: build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yaml
      - src/**
      - acceptance-test/**
      - template-project/**
      - gradle/**
      - '*.gradle'
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build.yaml
      - src/**
      - acceptance-test/**
      - template-project/**
      - gradle/**
      - '*.gradle'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: acceptance-test:example-docs

      - if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./acceptance-test/build/examples
          destination_dir: examples
